#!/bin/bash
## test-looping-skipping
## version 0.0.1 - initial
##################################################
test-looping-skipping() {
  for i in {1..99..2}
  do
   echo ${i}
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-looping-skipping
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 06 Feb 2019 12:43:49 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
