#!/bin/bash
## test-count-array-elements
## version 0.0.1 - initial
##################################################
test-count-array-elements() {
  mapfile arr
  echo ${#arr[@]}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-count-array-elements
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 31 Jan 2019 13:59:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
