#!/bin/bash
## test-awk-4
## version 0.0.1 - initial
##################################################
test-awk-4() {
  cat - | awk '
{
	if(NR%2==0) {
		print $(0)
	} else {
		printf $(0)";"
	}
}
'
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-awk-4
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 06 Feb 2019 08:32:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
