#!/bin/bash
## test-middle-of-text-file
## version 0.0.1 - initial
##################################################
test-middle-of-text-file() {
  sed -n -e '12,22p' /dev/stdin
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-middle-of-text-file
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 04 Feb 2019 08:20:51 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
