#!/bin/bash
## test-tr-2
## version 0.0.1 - initial
##################################################
test-tr-2() {
  cat /dev/stdin \
  | tr -d "[:lower:]"
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-tr-2
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 04 Feb 2019 12:18:07 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
