#!/bin/bash
## test-grep-2
## version 0.0.1 - initial
##################################################
test-grep-2() {
  grep -i -e '\sthe\s' -e 'the\s' -
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-grep-2
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 13:20:44 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
