#!/bin/bash
## test-triangles
## version 0.0.1 - initial 
##################################################
test-triangles() {
read -r x
read -r y
read -r z
count=0
test ! ${x} -eq ${y} || count=$(( count + 1 ))
test ! ${x} -eq ${z} || count=$(( count + 1 ))
test ! ${y} -eq ${z} || count=$(( count + 1 ))
case ${count} in 
0) echo SCALENE ;;
1) echo ISOSCELES ;;
2|3)  echo EQUILATERAL ;;
esac
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-triangles
##################################################
## generated by create-stub2.sh v0.1.1
## on Wed, 23 Jan 2019 08:32:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
