#!/bin/bash
## test-filter-array-patterns
## version 0.0.1 - initial
##################################################
test-filter-array-patterns() {
  mapfile arr
  output=$( echo "${arr[@]}" | grep -v -e '[aA]' )
  echo ${output/\s/}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-filter-array-patterns
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 12:17:47 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
