#!/bin/bash
## test-grep-3
## version 0.0.1 - initial
##################################################
test-grep-3() {
  grep -i \
  -e '\sthe\s' -e 'the\s' \
  -e '\sthat\s' -e 'that\s' \
  -e '\sthen \s' -e 'then\s' \
  -e '\sthose \s' -e 'those\s' \
  -
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-grep-3
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 13:28:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
