#!/bin/bash
## test-world-numbers
## =stub=
## version 0.0.0 - stub
##################################################
test-world-numbers() {
 declare -a args
 read -r z
 x=${z}
 read -r z
 y=${z}
 echo ${x}
 echo ${y}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-world-numbers
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 21 Jan 2019 16:38:45 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
