#!/bin/bash
## test-grep-a
## version 0.0.1 - initial
##################################################
test-grep-a() {
 true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-grep-a
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 13:29:27 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
