#!/bin/bash
## test-sed-2
## version 0.0.1 - initial
##################################################
test-sed-2() {
  sed -e 's/thy /your /gi' -
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-sed-2
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 13:50:27 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
