#!/bin/bash
## test-average
## - computes average
## version 0.0.1 - initial 
##################################################
car() {
  echo ${1}
}
cdr() {
  echo ${@:2}
}
sum() {
  local sum
  sum=0
  for i in ${@}
  do
    sum=$(( sum + i ))
  done 
  echo ${sum}
}
decimals() {
  cat /dev/stdin \
  | grep '[.].*' --only-matching
}
integer() {
  cat /dev/stdin \
  | grep '^[^.]*' --only-matching
}
round() {
  echo "${integer}.${decimals_1}${decimals_2}${decimals_3}"
}
test-average() {
  n=$( car $( cat ${infile} ) )
  x=$( cdr $( cat ${infile} ) )
  output=$( echo "scale=4; $( sum ${x} ) / ${n}" | bc  )
integer=$( echo ${output} | integer )
decimals=$( echo ${output} | decimals )
decimals_1=${decimals:1:1}
decimals_2=${decimals:2:1}
decimals_3=${decimals:3:1}
decimals_4=${decimals:4:1}
test ! ${decimals_4} -ge 5 || {
  decimals_3=$(( decimals_3 + 1 ))
}
test ! ${decimals_3} -ge 10 || {
  decimals_3=$(( decimals_3 + 1 ))
}
test ! ${decimals_2} -ge 10 || {
  decimals_3=$(( decimals_3 + 1 ))
}
test ! ${decimals_1} -ge 10 || {
  integer=$(( integer + 1 ))
}
echo "${integer}.${decimals_1}${decimals_2}${decimals_3}"
}
##################################################
if [ ${#} -eq 0 ] 
then
 infile=/dev/stdin
else
 exit 1 # wrong args
fi
##################################################
test-average
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 28 Jan 2019 12:33:40 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
