#!/bin/bash
## test-sort-1
## version 0.0.1 - initial
##################################################
test-sort-1() {
  cat /dev/stdin \
  | sort 
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-sort-1
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 04 Feb 2019 13:49:27 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
