#!/bin/bash
## test-sort-3
## version 0.0.1 - initial
##################################################
test-sort-3() {
  cat /dev/stdin \
  | sort --numeric-sort
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-sort-3
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 04 Feb 2019 13:51:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
