#!/bin/bash
## test-cut-2
## version 0.0.1 - initial
##################################################
test-cut-2() {
  cut -c 2,7 /dev/stdin
  return
  read -r line
  while [ "${line}" ]
  do
    cat << EOF
${line:1:1}${line:6:1}
EOF
    read -r line
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-cut-2
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 03 Feb 2019 15:16:22 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
