#!/bin/bash
## test-paste-2
## version 0.0.1 - initial
##################################################
sanitize() {
  cat /dev/stdin \
  | sed \
    -e 's/^\s*//' \
    -e 's/\s*$//'
}
shopt -s expand_aliases
alias remove-last-char="sed -e 's/.$//'"
tr() {
  cat /dev/stdin | xxd -ps | sed -e "s/${1}/${2}/g" | xxd -ps -r
}
tr-nl2semicolon() {
  cat /dev/stdin | tr 0a 3b
}
test-paste-2() {
  i=0
  read -r line
  while [ "${line}" ]
  do
   echo "${line}" | tr-nl2semicolon
   read -r line
   i=$(( i + 1 ))
   test ! $(( i % 3 )) -eq 0 || {
     echo ""
     i=0
   }
  done | remove-last-char
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-paste-2
##################################################
## generated by create-stub2.sh v0.1.1
## on Fri, 01 Feb 2019 13:49:45 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
