#!/bin/bash
## test-read-array
## version 0.0.1 - initial
##################################################
test-read-array() {
  mapfile arr
  echo ${arr[@]}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-read-array
##################################################
## generated by create-stub2.sh v0.1.2
## on Tue, 05 Feb 2019 12:06:41 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
