#!/bin/bash
## test-sort-7
## version 0.0.1 - initial
##################################################
test-sort-7() {
  cat /dev/stdin \
  | sort '-t|' -k2 --numeric --reverse
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-sort-7
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 04 Feb 2019 22:53:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
