#!/bin/bash
## test-replace-first-capital-for-each-element
## version 0.0.1 - initial
##################################################
test-replace-first-capital-for-each-element() {
  #cat /dev/stdin \
  #| sed -e 's/[A-Z]/./'
  mapfile arr
  echo ${arr[@]/[A-Z]/.}
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-replace-first-capital-for-each-element
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 31 Jan 2019 16:57:39 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
