#!/bin/bash
## test-awk-3
## version 0.0.1 - initial
##################################################
test-awk-3() {
  cat - | awk '
{
	average=($(2)+$(3)+$(4))/3
	if(average>=80)
		print $(0)" : A"
	else if(average>=60)
		print $(0)" : B"
	else if(average>=50)
		print $(0)" : C"
	else
		print $(0)" : FAIL"
}
'
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-awk-3
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 06 Feb 2019 08:27:02 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
