#!/bin/bash
## test-looping-numbers
## version 0.0.1 - initial
##################################################
test-looping-numbers() {
  for i in {1..50}
  do
    echo ${i}
  done
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-looping-numbers
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 06 Feb 2019 12:45:00 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
