#!/bin/bash
## test-uniq-4
## version 0.0.1 - initial
##################################################
strip-leading-whitespace() {
  cat /dev/stdin \
  | sed 's/^\s\+//'
}
list-uniq() {
  cat /dev/stdin \
  | uniq -c \
  | strip-leading-whitespace
}
car() {
  echo "${1}"
}
cdr() {
  echo "${@:2}"
}
testing() {
  read -r line
  while [ "${line}" ]
  do
   #set -v -x
   #test ! "${last}" = 1 || {
     test ! "$( car ${line} )" = 1 || {
       cdr ${line}
     }
   #}
   #set +v +x
   last=$( car ${line} )
   read -r line
  done
}
test-uniq-4() {

  #cat /dev/stdin
  #echo ""

  #list-uniq
  #echo "" 

  list-uniq \
  | testing 

}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-uniq-4
##################################################
## generated by create-stub2.sh v0.1.1
## on Fri, 01 Feb 2019 12:04:33 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
