#!/bin/bash
## test-uniq-1
## version 0.0.1 - initial
##################################################
test-uniq-1() {
  cat /dev/stdin \
  | uniq
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-uniq-1
##################################################
## generated by create-stub2.sh v0.1.1
## on Fri, 01 Feb 2019 11:56:35 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
