#!/bin/bash
## test-grep-1
## version 0.0.1 - initial
##################################################
test-grep-1() {
  grep -i -e '\sthe\s' -
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-grep-1
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 06 Feb 2019 12:38:59 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
